Last CI

diff --git a/.github/workflows/developer_ci.yml b/.github/workflows/developer_ci.yml
--- a/.github/workflows/developer_ci.yml
+++ b/.github/workflows/developer_ci.yml
@@ -3,12 +3,9 @@ name: Developer CI
 on:
   
   pull_request:
-    paths:    
-      - '.github/workflows/*.yml'
-
-  pull_request_target:
-    paths-ignore:    
-      - '.github/workflows/*.yml'    
+    # CI is disbabled if ONLY workflow files are changed
+    paths-ignore:
+      - '.github/workflows/**'
 
 env:
   QA_TIMEOUT_PER_TEST: 150
@@ -17,68 +14,91 @@ env:
 
 jobs:
 
-  build:
-    if: ${{ github.repository_owner == 'OpenRadioss' }}
-    # concurrency: 
-    #   group: ${{ github.ref_name }}
-    #   cancel-in-progress: true
-
-    # DEV ONLY # runs-on: ["build","dev_devci"]
-    runs-on: ["build","developer_ci"]
+  # This job is a guard to avoid running CI if workflows files are changed (even if they are not the only ones)
+  guard:
+    runs-on: developer_ci   
     container: 
-      image: fr-qafactorydev.europe.altair.com/build-linux64_gf:cos8-ompi411-devts11
-      credentials: 
-        username: ${{secrets.DOCKER_REGISTRY_USER}}
-        password: ${{secrets.DOCKER_REGISTRY_PASSWD}}
-      volumes: 
-        - /etc/localtime:/etc/localtime:ro
-
-    env:
-      BUILD_NB_THREAD: 2
-
-    strategy:
-      # If one job fails othere are canceled
-      fail-fast: true
-      matrix:
-        include:
-          - build: starter_linux64_gf
-            precision: dp
-            os: linux64
-            binary: starter
-
-  #         # - build: starter_linux64_gf_sp 
-  #         #   precision: sp
-  #         #   os: linux64
-  #         #   binary: starter
-
-  #         # - build: engine_linux64_gf_ompi
-  #         #   precision: dp
-  #         #   os: linux64
-  #         #   binary: engine
-  #         #   mpi: ompi
-
-  #         # - build: engine_linux64_gf_ompi_sp
-  #         #   precision: sp
-  #         #   os: linux64 
-  #         #   binary: engine
-  #         #   mpi: ompi
-
-  #         # - build: engine_linux64_gf
-  #         #   precision: dp
-  #         #   os: linux64
-  #         #   binary: engine
-
-  #         # - build: engine_linux64_gf_sp
-  #         #   precision: sp
-  #         #   os: linux64 
-  #         #   binary: engine
+      image: fr-qafactorydev.europe.altair.com/common-linux64
 
     steps:
-
-      - name: Clean local exe dir
+      - uses: actions/checkout@v4
+      - name: Detect workflow changes
         run: |
-          rm -rf exec
-          md5sum exec/* || echo "Nothing in exec/" 
+          # fetch base branch
+          git fetch origin ${{ github.event.pull_request.base.ref }} --depth=1
+          
+          # list changed files in the PR
+          changed=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }})
+          echo "Files changed in this PR:"
+          echo "$changed"
+          echo "-----"
+
+          # check if workflow or other sensitive dirs were modified
+          if echo "$changed" | grep -E '^\.github/workflows/'; then
+            echo "::error::Workflow files modified — stopping CI for safety."
+            exit 1
+          fi
+
+  # build:
+  #   needs: guard
+  #   if: ${{ github.repository_owner == 'OpenRadioss' }}
+  #   # concurrency: 
+  #   #   group: ${{ github.ref_name }}
+  #   #   cancel-in-progress: true
+
+  #   # DEV ONLY # runs-on: ["build","dev_devci"]
+  #   runs-on: ["build","developer_ci"]
+  #   container: 
+  #     image: fr-qafactorydev.europe.altair.com/build-linux64_gf:cos8-ompi411-devts11
+  #     volumes: 
+  #       - /etc/localtime:/etc/localtime:ro
+
+  #   env:
+  #     BUILD_NB_THREAD: 2
+
+  #   strategy:
+  #     # If one job fails othere are canceled
+  #     fail-fast: true
+  #     matrix:
+  #       include:
+  #         - build: starter_linux64_gf
+  #           precision: dp
+  #           os: linux64
+  #           binary: starter
+
+  #         - build: starter_linux64_gf_sp 
+  #           precision: sp
+  #           os: linux64
+  #           binary: starter
+
+  #         - build: engine_linux64_gf_ompi
+  #           precision: dp
+  #           os: linux64
+  #           binary: engine
+  #           mpi: ompi
+
+  #         - build: engine_linux64_gf_ompi_sp
+  #           precision: sp
+  #           os: linux64 
+  #           binary: engine
+  #           mpi: ompi
+
+  #         - build: engine_linux64_gf
+  #           precision: dp
+  #           os: linux64
+  #           binary: engine
+
+  #         - build: engine_linux64_gf_sp
+  #           precision: sp
+  #           os: linux64 
+  #           binary: engine
+
+  #   steps:
+
+  #     - name: Clean local exe dir
+  #       run: |
+  #         rm -rf exec
+  #         md5sum exec/* || echo "Nothing in exec/" 
 
   #     # Get last git modifications, WS is not persistent here
   #     - uses: actions/checkout@v4
@@ -130,6 +150,7 @@ jobs:
   #       if: ${{ matrix.build == 'starter_linux64_gf' }}
 
   # code-analysis:
+  #   needs: guard
   #   # We execute after all builds (in // with QA)
   #   if: ${{ github.repository_owner == 'OpenRadioss' }}
 
@@ -137,9 +158,6 @@ jobs:
   #   runs-on: ["build","developer_ci"]
   #   container: 
   #     image: fr-qafactorydev.europe.altair.com/build-linux64_gf:cos8-ompi411-devts11
-  #     credentials: 
-  #       username: ${{secrets.DOCKER_REGISTRY_USER}}
-  #       password: ${{secrets.DOCKER_REGISTRY_PASSWD}}
   #     volumes: 
   #       - /etc/localtime:/etc/localtime:ro
 
@@ -212,9 +230,6 @@ jobs:
   #   runs-on: ["qa_${{ matrix.os }}","developer_ci"]
   #   container: 
   #     image: fr-qafactorydev.europe.altair.com/qa-linux64_gf:cos8-ompi411
-  #     credentials: 
-  #       username: ${{secrets.DOCKER_REGISTRY_USER}}
-  #       password: ${{secrets.DOCKER_REGISTRY_PASSWD}}
   #     volumes: 
   #       - /etc/localtime:/etc/localtime:ro
 
