Update developer_ci.yml

diff --git a/.github/workflows/developer_ci.yml b/.github/workflows/developer_ci.yml
--- a/.github/workflows/developer_ci.yml
+++ b/.github/workflows/developer_ci.yml
@@ -3,9 +3,7 @@ name: Developer CI
 on:
   
   pull_request:
-    # CI is disbabled if ONLY workflow files are changed
-    paths-ignore:
-      - '.github/workflows/**'
+
 
 env:
   QA_TIMEOUT_PER_TEST: 150
@@ -24,20 +22,21 @@ jobs:
       - uses: actions/checkout@v4
       - name: Detect workflow changes
         run: |
-          # fetch base branch
-          git fetch origin ${{ github.event.pull_request.base.ref }} --depth=1
+          echo "This is original CI from main"
+          # # fetch base branch
+          # git fetch origin ${{ github.event.pull_request.base.ref }} --depth=1
           
-          # list changed files in the PR
-          changed=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }})
-          echo "Files changed in this PR:"
-          echo "$changed"
-          echo "-----"
+          # # list changed files in the PR
+          # changed=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }})
+          # echo "Files changed in this PR:"
+          # echo "$changed"
+          # echo "-----"
 
-          # check if workflow or other sensitive dirs were modified
-          if echo "$changed" | grep -E '^\.github/workflows/'; then
-            echo "::error::Workflow files modified — stopping CI for safety."
-            exit 1
-          fi
+          # # check if workflow or other sensitive dirs were modified
+          # if echo "$changed" | grep -E '^\.github/workflows/'; then
+          #   echo "::error::Workflow files modified — stopping CI for safety."
+          #   exit 1
+          # fi
 
   # build:
   #   needs: guard
